//
//  ReactNativeCapfaceSdk.swift
//  ReactNativeCapfaceSdk
//
//  Created by Nayara Dias, Bruno Fialho and Daniel Sansão on 04/09/23.
//  Copyright © 2023 Capitual. All rights reserved.
//


import Foundation
import FaceTecSDK
import LocalAuthentication

@objc(ReactNativeCapfaceSdk)
class ReactNativeCapfaceSdk: RCTEventEmitter, URLSessionDelegate {
    public static var emitter: RCTEventEmitter!
    var faceTecViewController: FaceTecViewController!
    var isInitialized: Bool = false;
    
    override init() {
        super.init();
        ReactNativeCapfaceSdk.emitter = self;
    }
    
    private func isDeveloperMode(_ params: NSDictionary) -> Bool {
        return params.value(forKey: "isDeveloperMode") as! Bool;
    }
    
    private func handleFaceTecConfiguration(_ params: NSDictionary, headers: NSDictionary) {
        Config.setDevice(params.value(forKey: "device") as! String);
        Config.setUrl(params.value(forKey: "url") as! String);
        Config.setKey(params.value(forKey: "key") as! String);
        Config.setProductionKeyText(params.value(forKey: "productionKey") as! String);
        Config.setHeaders(headers);
    }
    
    @objc func initializeSdk(_ params: NSDictionary, headers: NSDictionary, callback: @escaping RCTResponseSenderBlock) -> Void {
        DispatchQueue.main.async {
            self.faceTecViewController = FaceTecViewController();
            self.handleTheme(Config.Theme);
            
            if params.count == 0 {
                self.isInitialized = false;
                callback([false]);
                print("No parameters provided!");
                return;
            }
            
            self.handleFaceTecConfiguration(params, headers: headers);
            
            if (Config.hasConfig()) {
                Config.initializeFaceTecSDKFromAutogeneratedConfig(self.isDeveloperMode(params), completion: { initializationSuccessful in
                    self.isInitialized = initializationSuccessful;
                    callback([initializationSuccessful]);
                })
            } else {
                self.isInitialized = false;
                callback([false]);
                print("Configuration SDK doesn't exists!");
            }
        }
    }
    
    @objc override static func requiresMainQueueSetup() -> Bool {
        return true;
    }
    
    @objc override func constantsToExport() -> [AnyHashable : Any]! {
        return nil;
    }
    
    @objc override func startObserving() {}
    
    @objc override func stopObserving() {}
    
    @objc override func supportedEvents() -> [String]! {
        return ["onCloseModal"];
    }
    
    @objc func handleLivenessCheck(_ data: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
        if self.isInitialized {
            self.faceTecViewController.onLivenessCheck(data, resolve: resolve, reject: reject);
        } else {
            print("SDK doesn't initialized!");
            return reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized", nil);
        }
    }
    
    @objc func handleEnrollUser(_ data: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
        if self.isInitialized {
            self.faceTecViewController.onEnrollUser(data, resolve: resolve, reject: reject);
        } else {
            print("SDK doesn't initialized!");
            return reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized", nil);
        }
    }
    
    @objc func handleAuthenticateUser(_ data: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
        if self.isInitialized {
            self.faceTecViewController.onAuthenticateUser(data, resolve: resolve, reject: reject);
        } else {
            print("SDK doesn't initialized!");
            return reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized", nil);
        }
    }
    
    @objc func handlePhotoIDMatch(_ data: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
        if self.isInitialized {
            self.faceTecViewController.onPhotoIDMatch(data, resolve: resolve, reject: reject);
        } else {
            print("SDK doesn't initialized!");
            return reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized", nil);
        }
    }
    
    @objc func handlePhotoIDScan(_ data: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
        if self.isInitialized {
            self.faceTecViewController.onPhotoIDScan(data, resolve: resolve, reject: reject);
        } else {
            print("SDK doesn't initialized!");
            return reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized", nil);
        }
    }
    
    @objc func handleTheme(_ options: NSDictionary?) {
        ThemeHelpers.setAppTheme(options);
    }
}
